import React, { useState, useEffect } from 'react'
import { Download, Save, FolderOpen, FileText, Package, Settings, ChevronRight, ChevronDown } from 'lucide-react'

interface FlutterProject {
  files: Record<string, string>
  mainFile?: string
}

interface ProjectPanelProps {
  code: string
  project?: FlutterProject | null
  prompt: string
  selectedFile?: string
  onFileSelect?: (path: string) => void
  onSave: () => void
  onExport: () => void
}

const ProjectPanel: React.FC<ProjectPanelProps> = ({ 
  code, 
  project, 
  prompt: _prompt, 
  selectedFile = 'lib/main.dart',
  onFileSelect,
  onSave, 
  onExport 
}) => {
  const [activeTab, setActiveTab] = useState<'files' | 'dependencies' | 'settings'>('files')
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set(['lib']))

  // Auto-expand all folders when project has nested files (e.g. lib/screens/, lib/models/)
  useEffect(() => {
    if (!project?.files || Object.keys(project.files).length === 0) return
    const folders = new Set<string>()
    Object.keys(project.files).forEach((path) => {
      const parts = path.split('/')
      for (let i = 1; i < parts.length; i++) {
        folders.add(parts.slice(0, i).join('/'))
      }
    })
    if (folders.size > 0) setExpandedFolders(folders)
  }, [project?.files])

  // Extract dependencies from code
  const extractDependencies = (code: string): string[] => {
    const deps: string[] = []
    const importMatches = code.matchAll(/import\s+['"]([^'"]+)['"]/g)
    for (const match of importMatches) {
      const importPath = match[1]
      if (importPath.startsWith('package:')) {
        deps.push(importPath.replace('package:', ''))
      }
    }
    
    // Common Flutter dependencies
    if (code.includes('http')) deps.push('http: ^1.1.0')
    if (code.includes('provider')) deps.push('provider: ^6.0.5')
    if (code.includes('shared_preferences')) deps.push('shared_preferences: ^2.2.2')
    
    return deps.length > 0 ? deps : ['No external dependencies']
  }

  const dependencies = extractDependencies(code)

  const generatePubspec = () => {
    return `name: flutter_app
description: A Flutter app generated by FlutterForge AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
${dependencies.filter(d => !d.includes('No external')).map(d => `  ${d}`).join('\n')}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
`
  }

  return (
    <div className="h-full flex flex-col bg-obsidian-800/30 border-l border-obsidian-700/30">
      {/* Header */}
      <div className="h-10 border-b border-obsidian-700/30 flex items-center justify-between px-4 shrink-0">
        <div className="flex items-center gap-2">
          <FolderOpen className="w-4 h-4 text-cyan-400" />
          <span className="text-sm text-obsidian-300">Project</span>
        </div>
        <div className="flex items-center gap-1">
          <button
            onClick={onSave}
            className="p-1.5 hover:bg-obsidian-700/30 rounded transition-colors"
            title="Save project"
          >
            <Save className="w-4 h-4 text-obsidian-400" />
          </button>
          <button
            onClick={onExport}
            className="p-1.5 hover:bg-obsidian-700/30 rounded transition-colors"
            title="Export Flutter project"
          >
            <Download className="w-4 h-4 text-obsidian-400" />
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-obsidian-700/30">
        <button
          onClick={() => setActiveTab('files')}
          className={`px-4 py-2 text-xs font-medium transition-colors border-b-2 ${
            activeTab === 'files'
              ? 'text-cyan-400 border-cyan-400'
              : 'text-obsidian-400 border-transparent hover:text-obsidian-200'
          }`}
        >
          <FileText className="w-3 h-3 inline mr-1.5" />
          Files
        </button>
        <button
          onClick={() => setActiveTab('dependencies')}
          className={`px-4 py-2 text-xs font-medium transition-colors border-b-2 ${
            activeTab === 'dependencies'
              ? 'text-cyan-400 border-cyan-400'
              : 'text-obsidian-400 border-transparent hover:text-obsidian-200'
          }`}
        >
          <Package className="w-3 h-3 inline mr-1.5" />
          Dependencies
        </button>
        <button
          onClick={() => setActiveTab('settings')}
          className={`px-4 py-2 text-xs font-medium transition-colors border-b-2 ${
            activeTab === 'settings'
              ? 'text-cyan-400 border-cyan-400'
              : 'text-obsidian-400 border-transparent hover:text-obsidian-200'
          }`}
        >
          <Settings className="w-3 h-3 inline mr-1.5" />
          Settings
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto scrollbar-thin p-4">
        {activeTab === 'files' && (
          <div className="space-y-1">
            {project && project.files && Object.keys(project.files).length > 0 ? (
              <>
                <div className="text-xs text-obsidian-400 mb-2 px-2">
                  {Object.keys(project.files).length} file{Object.keys(project.files).length !== 1 ? 's' : ''}
                </div>
                <FileTree
                  files={project.files}
                  selectedFile={selectedFile}
                  expandedFolders={expandedFolders}
                  onFileSelect={onFileSelect}
                  onToggleFolder={(folder) => {
                    const newExpanded = new Set(expandedFolders)
                    if (newExpanded.has(folder)) {
                      newExpanded.delete(folder)
                    } else {
                      newExpanded.add(folder)
                    }
                    setExpandedFolders(newExpanded)
                  }}
                />
              </>
            ) : (
              <div className="space-y-2">
                <div 
                  className={`bg-obsidian-700/30 border rounded-lg p-3 cursor-pointer transition-colors ${
                    selectedFile === 'lib/main.dart' 
                      ? 'border-cyan-400/50 bg-cyan-400/10' 
                      : 'border-obsidian-600/30 hover:border-obsidian-500/50'
                  }`}
                  onClick={() => onFileSelect?.('lib/main.dart')}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <FileText className="w-4 h-4 text-cyan-400" />
                    <span className="text-sm font-medium text-obsidian-200">lib/main.dart</span>
                  </div>
                  <p className="text-xs text-obsidian-400">Main application file</p>
                </div>
                
                <div 
                  className={`bg-obsidian-700/30 border rounded-lg p-3 cursor-pointer transition-colors ${
                    selectedFile === 'pubspec.yaml' 
                      ? 'border-cyan-400/50 bg-cyan-400/10' 
                      : 'border-obsidian-600/30 hover:border-obsidian-500/50'
                  }`}
                  onClick={() => onFileSelect?.('pubspec.yaml')}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <Package className="w-4 h-4 text-violet-400" />
                    <span className="text-sm font-medium text-obsidian-200">pubspec.yaml</span>
                  </div>
                  <p className="text-xs text-obsidian-400">Dependencies and project config</p>
                </div>
              </div>
            )}
          </div>
        )}

        {activeTab === 'dependencies' && (
          <div className="space-y-2">
            <div className="mb-4">
              <h3 className="text-sm font-medium text-obsidian-200 mb-2">Required Packages</h3>
              <div className="space-y-1.5">
                {dependencies.map((dep, idx) => (
                  <div
                    key={idx}
                    className="bg-obsidian-700/30 border border-obsidian-600/30 rounded-lg px-3 py-2"
                  >
                    <code className="text-xs text-cyan-400 font-mono">{dep}</code>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="bg-obsidian-700/30 border border-obsidian-600/30 rounded-lg p-3">
              <h3 className="text-xs font-medium text-obsidian-200 mb-2">pubspec.yaml</h3>
              <pre className="text-xs text-obsidian-300 font-mono overflow-x-auto">
                <code>{generatePubspec()}</code>
              </pre>
            </div>
          </div>
        )}

        {activeTab === 'settings' && (
          <div className="space-y-4">
            <div>
              <h3 className="text-sm font-medium text-obsidian-200 mb-3">Flutter Version</h3>
              <select className="w-full px-3 py-2 bg-obsidian-700/30 border border-obsidian-600/30 rounded-lg text-sm text-obsidian-200 focus:outline-none focus:border-cyan-400/50">
                <option>3.24.0 (latest stable)</option>
                <option>3.22.0</option>
                <option>3.19.0</option>
              </select>
            </div>
            
            <div>
              <h3 className="text-sm font-medium text-obsidian-200 mb-3">Platform Support</h3>
              <div className="space-y-2">
                {['iOS', 'Android', 'Web', 'Windows', 'macOS', 'Linux'].map((platform) => (
                  <label key={platform} className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      defaultChecked={platform === 'iOS' || platform === 'Android'}
                      className="w-4 h-4 rounded bg-obsidian-700/50 border-obsidian-600/30 text-cyan-400 focus:ring-cyan-400/50"
                    />
                    <span className="text-sm text-obsidian-300">{platform}</span>
                  </label>
                ))}
              </div>
            </div>
            
            <div>
              <h3 className="text-sm font-medium text-obsidian-200 mb-3">Code Generation</h3>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  defaultChecked
                  className="w-4 h-4 rounded bg-obsidian-700/50 border-obsidian-600/30 text-cyan-400 focus:ring-cyan-400/50"
                />
                <span className="text-sm text-obsidian-300">Include comments</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer mt-2">
                <input
                  type="checkbox"
                  defaultChecked
                  className="w-4 h-4 rounded bg-obsidian-700/50 border-obsidian-600/30 text-cyan-400 focus:ring-cyan-400/50"
                />
                <span className="text-sm text-obsidian-300">Format code automatically</span>
              </label>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

// File Tree Component
interface FileTreeProps {
  files: Record<string, string>
  selectedFile: string
  expandedFolders: Set<string>
  onFileSelect?: (path: string) => void
  onToggleFolder: (folder: string) => void
}

const FileTree: React.FC<FileTreeProps> = ({ 
  files, 
  selectedFile, 
  expandedFolders, 
  onFileSelect, 
  onToggleFolder 
}) => {
  // Simple flat list of files with folder grouping
  const fileList = Object.keys(files).sort()

  // Group by folder
  const folderMap: Record<string, string[]> = {}
  fileList.forEach(path => {
    const parts = path.split('/')
    if (parts.length > 1) {
      const folder = parts.slice(0, -1).join('/')
      if (!folderMap[folder]) folderMap[folder] = []
      folderMap[folder].push(path)
    } else {
      if (!folderMap['']) folderMap[''] = []
      folderMap[''].push(path)
    }
  })
  
  const getFileIcon = (path: string) => {
    if (path.endsWith('.dart')) return '📄'
    if (path.endsWith('.yaml') || path.endsWith('.yml')) return '⚙️'
    if (path.endsWith('.md')) return '📝'
    if (path.endsWith('.gitignore')) return '🚫'
    return '📄'
  }
  
  return (
    <div className="space-y-0.5">
      {Object.entries(folderMap).sort(([a], [b]) => {
        if (a === '') return 1
        if (b === '') return -1
        return a.localeCompare(b)
      }).map(([folder, filePaths]) => {
        if (folder === '') {
          // Root level files
          return filePaths.map(path => {
            const fileName = path
            const isSelected = selectedFile === path
            return (
              <div
                key={path}
                onClick={(e) => { e.stopPropagation(); onFileSelect?.(path) }}
                role="button"
                tabIndex={0}
                onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onFileSelect?.(path) } }}
                title={path}
                className={`flex items-center gap-2 px-2 py-1.5 rounded text-sm cursor-pointer transition-colors ${
                  isSelected
                    ? 'bg-cyan-400/20 text-cyan-400 border border-cyan-400/30'
                    : 'text-obsidian-300 hover:bg-obsidian-700/30'
                }`}
              >
                <span className="text-xs">{getFileIcon(path)}</span>
                <span className="font-mono text-xs truncate">{fileName}</span>
              </div>
            )
          })
        } else {
          // Folder with files
          const isExpanded = expandedFolders.has(folder)
          return (
            <div key={folder}>
              <div
                onClick={() => onToggleFolder(folder)}
                className="flex items-center gap-1 px-2 py-1.5 rounded text-sm cursor-pointer hover:bg-obsidian-700/30 transition-colors"
              >
                {isExpanded ? (
                  <ChevronDown className="w-3 h-3 text-obsidian-400" />
                ) : (
                  <ChevronRight className="w-3 h-3 text-obsidian-400" />
                )}
                <FolderOpen className="w-3 h-3 text-violet-400" />
                <span className="text-obsidian-200 font-medium">{folder}</span>
              </div>
              {isExpanded && (
                <div className="ml-4">
                  {filePaths.map(path => {
                    const fileName = path.split('/').pop() || path
                    const isSelected = selectedFile === path
                    return (
                      <div
                        key={path}
                        onClick={(e) => { e.stopPropagation(); onFileSelect?.(path) }}
                        role="button"
                        tabIndex={0}
                        onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onFileSelect?.(path) } }}
                        title={path}
                        className={`flex items-center gap-2 px-2 py-1.5 rounded text-sm cursor-pointer transition-colors ${
                          isSelected
                            ? 'bg-cyan-400/20 text-cyan-400 border border-cyan-400/30'
                            : 'text-obsidian-300 hover:bg-obsidian-700/30'
                        }`}
                      >
                        <span className="text-xs">{getFileIcon(path)}</span>
                        <span className="font-mono text-xs truncate">{fileName}</span>
                      </div>
                    )
                  })}
                </div>
              )}
            </div>
          )
        }
      })}
    </div>
  )
}

export default ProjectPanel
